remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: cse15l-lab-reports
description: tutorial blogs :)
date: `r format(Sys.time(), '%d %B, %Y')`
author: Jose Hugo
show_downloads: true
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /img/logo.jpg
        height: 630
        width: 1200
